### PR TITLE
ring/ring.go: reactive update of metrics

### LINKED ISSUE #108: Ring metrics updated slowly
A sort of regression as PR #50 removed collecting metrics directly. Now readers of metrics, for example e2e tests have to wait for a possible 10s (hard-coded) to have updated metrics. This means a big slowdown in tests and possible loss of information.

### PR DESCRIPTION
**Pull request by krajorama**
**What this PR does**:
When writing e2e tests for services using Ring, it is natural to wait
for having all tokens assigned. With the default 10s interval for updating
metrics, this slows down tests considerably. This was not the case before
PR 50 where metrics were collected on request.

This commit moves updateMetrics into updateRingState, but also optimizes
away updates to ring token ownership metrics when only state or timestamps
have changed and skips the metrics entirely when nothing changed.
The reasoning is that changes to the ring tokens are infrequent so we
can afford a relatively heavy operation.

**Which issue(s) this PR fixes**:

Fixes #108 

**Checklist**
- [x] Tests updated
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: ring/ring.go [hunk 1]
```diff
@@ -286,14 +286,13 @@ func (r *Ring) starting(ctx context.Context) error {
...
-		ticker := time.NewTicker(10 * time.Second)
-		defer ticker.Stop()
 
+	metricChan := make(chan struct{}, 1)
+	go func() {
 		for {
 			select {
-			case <-ticker.C:
+			case <-metricChan:
+				time.After(time.Second) // debounce and avoid consuming too much CPU
```
Comment (replay) [inline ring/ring.go:295]: why does this `time.After` reduce the CPU usage (based on comment)?

Comment (replay) [reply ring/ring.go:295]: Do I understand it correctly that the purpose of this is to prevent that `.updateRingMetrics()` gets called many times if there are many ring updates within a short time frame?

File: ring/ring.go [hunk 2]
```diff
@@ -564,12 +571,46 @@ func (r *Ring) countTokens() (map[string]uint32, map[string]uint32) {
...
+	ringTokens := ringDesc.GetTokens()
+	ringInstanceByToken := ringDesc.getTokensInfo()
+	owned := map[string]uint32{}
+	numTokens := map[string]uint32{}
+	for i, token := range ringTokens {
+		var diff uint32
+
+		// Compute how many tokens are within the range.
+		if i+1 == len(ringTokens) {
+			diff = (math.MaxUint32 - token) + ringTokens[0]
```
Comment (replay) [inline ring/ring.go:585]: is it guaranteed that the total ring size is always `math.MaxUint32`?

Comment (replay) [reply ring/ring.go:585]: Looks like it, because there are various places in the code which use `math.MaxUint32` in a similar way.

File: ring/ring.go (hunk 1 above)
Comment (krajorama) [reply ring/ring.go:295]: updateRingMetrics won't be called many times, since it's much slower than KV.Watch / updateRingState, so the metricChan buffer will sink events. On the other hand if there's a burst of activity it could be worth waiting a little bit (debounce) before calculating (although it doesn't effect our tests if I leave out debounce). And in case there's sustained events long term, then we'd get updateRingState executing continuously.

I must admit it's a bit overengineered and also delays cancelling the goroutine so I can remove it if you prefer?

Comment (replay) [reply ring/ring.go:295]: Thanks for explaining.

> I can remove it if you prefer

I think it's fine to keep it, but maybe the comment could explain it a bit more because at least for me it wasn't obvious what "debounce" means in this context.

File: ring/ring.go [hunk 3]
```diff
@@ -564,12 +571,46 @@ func (r *Ring) countTokens() (map[string]uint32, map[string]uint32) {
 	return numTokens, owned
 }
 
-// updateRingMetrics updates ring metrics.
+// countTokens returns the number of tokens and tokens within the range for each instance.
+func countTokensUtil(ringDesc *Desc) (map[string]uint32, map[string]uint32, int) {
```
Comment (replay) [inline ring/ring.go:575]: There is quite a bit of duplication between `Ring.countTokens()` and `countTokensUtil()` now. 
Couldn't `countTokensUtil` replace `Ring.countTokens()`?

File: ring/ring.go [hunk 4]
```diff
@@ -564,12 +571,46 @@ func (r *Ring) countTokens() (map[string]uint32, map[string]uint32) {
...
+		}
+	}
+
+	return numTokens, owned, len(ringTokens)
+}
+
 func (r *Ring) updateRingMetrics() {
-	r.mtx.RLock()
-	defer r.mtx.RUnlock()
+	r.mtx.Lock()
```
Comment (replay) [inline ring/ring.go:607]: why is the read lock not sufficient anymore?

**Review by replay — COMMENTED** [review]
The change makes sense to me, thanks! I just added some minor comments

File: ring/ring.go (hunk 4 above)
Comment (krajorama) [reply ring/ring.go:607]: woops, nice catch

File: ring/ring.go (hunk 3 above)
Comment (krajorama) [reply ring/ring.go:575]: working on it. Actually Ring.countTokens is only used at one more place in ring/http.go

File: ring/ring.go (hunk 2 above)
Comment (krajorama) [reply ring/ring.go:585]: I guess this is more of a convention that for example lifecycler and basic lifecycler follows. Not sure why you'd ever reduce the domain though as that just increases the chance of hash collisions.

Comment (pracucci) [reply ring/ring.go:585]: > is it guaranteed that the total ring size is always math.MaxUint32?

`math.MaxUint32` is the tokens space, which is fixed.

File: CHANGELOG.md [hunk 5]
```diff
@@ -26,5 +26,6 @@
 * [ENHANCEMENT] flagext: for cases such as `DeprecatedFlag()` that need a logger, add RegisterFlagsWithLogger. #80
 * [ENHANCEMENT] Added option to BasicLifecycler to keep instance in the ring when stopping. #97
 * [ENHANCEMENT] Add WaitRingTokensStability function to ring, to be able to wait on ring stability excluding allowed state transitions. #95
+* [ENHANCEMENT] Trigger metrics update instead of doing it periodically to speed up tests that wait for certain metrics. #107
```
Comment (pracucci) [inline CHANGELOG.md:29]: [nit]
```suggestion
* [ENHANCEMENT] Trigger metrics update on ring changes instead of doing it periodically to speed up tests that wait for certain metrics. #107
```

File: ring/ring.go (hunk 1 above)
Comment (pracucci) [reply ring/ring.go:295]: I agree on improving the comment.

Comment (pracucci) [inline ring/ring.go:295]: This is not a sleep. You need to wait for a message on the returned channel (and also handle `ctx.Done`). See example in doc:
https://pkg.go.dev/time#After

Comment (pracucci) [inline ring/ring.go:295]: We shouldn't wait 1 sec if it elapsed more than 1s since the last update. I think we need something slightly smarter here.

File: ring/ring.go [hunk 6]
```diff
@@ -601,7 +642,7 @@ func (r *Ring) updateRingMetrics() {
 	for state, timestamp := range oldestTimestampByState {
 		r.oldestTimestampGaugeVec.WithLabelValues(state).Set(float64(timestamp))
 	}
-	r.totalTokensGauge.Set(float64(len(r.ringTokens)))
+	r.totalTokensGauge.Set(float64(ringTokenCount))
```
Comment (pracucci) [inline ring/ring.go:645]: Why `len(r.ringTokens)` wasn't good enough? You can read it while the lock is held at the beginning of the function.

File: ring/ring.go (hunk 1 above)
Comment (krajorama) [reply ring/ring.go:295]: went with different solution

File: ring/ring.go (hunk 3 above)
Comment (krajorama) [reply ring/ring.go:575]: went with different solution

File: ring/ring.go (hunk 1 above)
Comment (krajorama) [reply ring/ring.go:295]: went with different solution

File: ring/ring.go (hunk 6 above)
Comment (krajorama) [reply ring/ring.go:645]: went with different solution

File: ring/ring.go (hunk 1 above)
Comment (krajorama) [reply ring/ring.go:295]: went with different solution

File: CHANGELOG.md (hunk 5 above)
Comment (krajorama) [reply CHANGELOG.md:29]: ack

**Comment by krajorama** [comment]
Based on comments by @pracucci and @replay  a simplified solution is presented measured with a new benchmark test.

Results show that updateRingState is already significantly slower in case there's a change to tokens (0.2ms/op vs 92ms/op) and adding in a modified updateMetrics is not of concern (0.3ms/op vs 146ms/op).

File: ring/ring.go [hunk 7]
```diff
@@ -285,21 +285,7 @@ func (r *Ring) starting(ctx context.Context) error {
...
-		for {
-			select {
-			case <-ticker.C:
-				r.updateRingMetrics()
-			case <-ctx.Done():
-				return
-			}
-		}
-	}()
+	r.updateRingMetrics(Different)
```
Comment (pracucci) [inline ring/ring.go:288]: It should run it taking the read lock.

File: ring/ring.go [hunk 8]
```diff
@@ -334,6 +320,7 @@ func (r *Ring) updateRingState(ringDesc *Desc) {
 		// when watching the ring for updates).
 		r.mtx.Lock()
 		r.ringDesc = ringDesc
+		r.updateRingMetrics(rc)
```
Comment (pracucci) [inline ring/ring.go:323]: [nit] Given this is the common case and given how easy it is to move it to read lock only, we could take the read lock only for this case.

File: ring/ring.go (hunk 7 above)
Comment (pracucci) [reply ring/ring.go:288]: Re-thinking it, may just be safer to take the read lock directly in `updateRingMetrics()`. Look at where `updateRingMetrics()` is called, it looks an easier change.

**Review by pracucci — APPROVED** [review]
LGTM! I would be glad if could take a look at a couple of nits before we merge.

File: ring/ring.go (hunk 7 above)
Comment (krajorama) [reply ring/ring.go:289]: Added locking around the initial metrics - since it's called just once and also due to upcoming PR 109, I used write lock. We discussed the locking IRL and opted to keep the locking outside updateRingMetrics

File: ring/ring.go (hunk 8 above)
Comment (krajorama) [reply ring/ring.go:325]: We discussed the locking IRL and opted to keep the locking outside updateRingMetrics
