### PR TITLE
fix(middleware): prevent idle cleanup from resetting connection TTL

### LINKED ISSUE #907: httpConnectionTTLMiddleware: removeExpiredConnection unconditionally re-creates cleaned-up entries
## Description

In `middleware/http_connection_ttl_middleware.go`, `removeExpiredConnection` calls `connectionState(conn)` as its first step. `connectionState` always creates a new map entry if one doesn't exist:

```go
func (m *httpConnectionTTLMiddleware) removeExpiredConnection(conn string) bool {
    state := m.connectionState(conn)  // creates entry if missing
    if !state.isExpired() {
        return false
    }
    // ...
}
```

```go
func (m *httpConnectionTTLMiddleware) connectionState(conn string) *connectionState {
    // ...
    state, cachedConn := m.connections[conn]
    if cachedConn {
        state.lastSeen = now
    } else {
        ttl := m.calculateTTL(conn)
        state = &connectionState{ttl: ttl, created: now, lastSeen: now}
        m.connections[conn] = state  // always creates
    }
    // ...
}
```

This means that if a connection was previously cleaned up (e.g. by the idle ticker in `removeIdleExpiredConnections`), the next request from the same `RemoteAddr` will:

1. **Re-create** the entry with a fresh TTL and `created` timestamp
2. Increment `totalOpenConnections` (phantom open)
3. See `isExpired() == false` (just created) and return false — no `Connection: close` is sent

The net effect is that an expired connection that was garbage-collected silently gets a brand new TTL instead of being immediately signalled to close.

### Suggested fix

Separate "get-or-create" from "get-if-exists". In `removeExpiredConnection`, use a read-only lookup. Only create new entries in `Wrap` (or a dedicated tracking method) when the connection is not being evicted.

### PR DESCRIPTION
**Pull request by aknuds1**
**What this PR does**:

The connection TTL middleware has two independent code paths sharing a `connections` map: `removeExpiredConnection` (called per request, enforces TTL) and `removeIdleExpiredConnections` (background ticker, garbage-collects entries for idle connections). When a connection's TTL has expired but no request has arrived yet to actually close the connection (via `removeExpiredConnection`), the idle cleanup can fire first and delete the middleware's tracked connection state. The next request then creates a fresh entry and a new TTL, via `removeExpiredConnection`. This can repeat on every idle gap, allowing a TCP connection to live indefinitely without being closed and then rotated.

This PR fixes the problem through two-phase idle cleanup:

- `removeIdleExpiredConnections` now **marks** idle-expired entries on the first pass (`idleExpired = true`) and **deletes** them on the second pass only if no request arrived in between. This preserves the entry so that `removeExpiredConnection` can still find it, check the original `created` time, and correctly send `Connection: close`.

A deterministic test using `testing/synctest` reproducing the scenario is added.

**Which issue(s) this PR fixes**:

Fixes #907 and #908

**Checklist**
- [x] Tests updated

---

> [!NOTE]
> **Medium Risk**
> Changes core connection-tracking/cleanup behavior and timing interactions between request handling and a background goroutine; mistakes could lead to leaked map entries or incorrect connection closing/metrics.
> 
> **Overview**
> Fixes a bug where the background idle-connection cleanup could delete a tracked connection before a subsequent request arrived, allowing the next request to recreate state and effectively reset the connection’s TTL.
> 
> `removeIdleExpiredConnections` now performs **two-phase cleanup** by first marking idle-expired entries (`idleExpired`) and only deleting them on a later pass if they remain idle, ensuring `removeExpiredConnection` can still enforce the original TTL. Tests were updated to stop the middleware in cleanup, and a new deterministic `testing/synctest` case covers the “idle cleanup then request” scenario and asserts `Connection: close` is sent and metrics reflect the close reason.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 266e9130733459f3ab7fa1b1097939b28814a3b2. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: middleware/http_connection_ttl_middleware.go [hunk 1]
```diff
@@ -140,25 +148,24 @@ func (m *httpConnectionTTLMiddleware) removeExpiredConnection(conn string) bool
 	m.connectionsMu.Lock()
 	state, exists := m.connections[conn]
 	if !exists {
-		state = &connectionState{
+		m.connections[conn] = &connectionState{
```
Comment (pracucci) [inline middleware/http_connection_ttl_middleware.go]: I think you can restore this function to the version in `main` to simplify the diff. There's no logic change here.

**Review by pracucci — COMMENTED** [review]
I can't see the bug you're trying to fix here. The PR and issue description are not much clear to me, and I honestly can't see what we're fixing.

File: middleware/http_connection_ttl_middleware.go (hunk 1 above)
Comment (aknuds1) [reply middleware/http_connection_ttl_middleware.go]: I will check.

Comment (aknuds1) [reply middleware/http_connection_ttl_middleware.go]: You're right @pracucci - this change was cosmetic, so I reverted it.

**Review by pracucci — APPROVED** [review]

**Comment by aknuds1** [comment]
@pracucci I also found there is the edge case of two idleness ticks occurring after the TTL is exceeded, but before the evicting request occurs. Like your Claude session said though, it appears impractical to fix.
